Controllers/ApplicationController.cs
using AnimalShelterProject.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelterProject.Controllers
{
    public class ApplicationController : Controller
    {

        ShelterDbContext _ShelterDbContext= new ShelterDbContext();



        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SubmitAnimal()
        {
            return View();
        }
        public IActionResult AddSubmission()
        {
            return View();
        }
        public IActionResult ApplyForAnimal()
        {
            return View();
        }
        public IActionResult ListSubmits()
        {
            var submitList = (from submit in _ShelterDbContext.Applications
                             where (submit.isSubmit) == true
                              select submit).Include(submit => submit.Person).ToList();
            return View(submitList);
        }
        public IActionResult ListApplies() 
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using AnimalShelterProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AnimalShelterProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonController.cs
using AnimalShelterProject.Data;
using AnimalShelterProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelterProject.Controllers
{
    public class PersonController : Controller
    {
        ShelterDbContext db = new ShelterDbContext();
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult SavePersonData(Person person)
        {
            if(ModelState.IsValid) 
            {
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            else
                return View("Error");
            
        }
    
        public IActionResult SavePerson() 
        {
            return View();
        }

    }
    
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div>

    <h4>
        Hoşgeldiniz! Lütfen devam yolu seçiniz:
    </h4>
     <a asp-controller="Application" asp-action="SubmitAnimal" class="btn btn-primary">Hayvan Gönder</a>
   @* <a asp-controller="Application" asp-action="ApplyForAnimal" class="btn btn-success">Hayvan Sahiplen</a>*@
    <a asp-controller="Application" asp-action="ListSubmits" class="btn btn-success">Hayvan Sahiplen</a>
    <a asp-controller="Person" asp-action="SavePerson" class="btn btn-success">Şahıs Ekle</a>

</div>